Repository CathyDolle/genshin, pull requests merged in 2020-11, with the labels that each got.

#8 chore(license)-MIT-🎉
  LICENSE.md
Labels: documentation

#10 chore(readme): remove CRA bullshit
  README.md
Labels: documentation

#14 fix(animation): back to exact timings
  src/components/Visual.jsx
Labels: bug

#15 fix external and remove useless external in all files
  src/data/news.js
  src/modules/TextContent/TextContent.jsx
  src/pages/Abyss.jsx
  src/pages/Debutant.jsx
  src/templates/VisualAndPosts.jsx
  src/utils/LinkOrExternal.jsx
Labels: enhancement

#19 fix(image): remove the small pixel on Sucrine
  src/assets/images/char/sucrose.png
Labels: bug

#20 Tweaking of Visual component animation
  src/App.jsx
  src/App.scss
  src/assets/images/char/paimon.png
  src/assets/images/char/qiqi.png
  src/assets/images/char/razor.png
  src/assets/images/char/sucrose.png
  src/assets/images/char/xiangling.png
  src/components/Visual.scss
Labels: enhancement

#32 test(utils): basic scenarios
  .eslintrc.js
  src/modules/TextContent/TextContent.jsx
  src/utils/LinkOrExternal.jsx
  src/utils/TextRenderer.jsx
  src/utils/__tests__/LinkOrExternal.test.jsx
  src/utils/__tests__/RenderWithNextLine.test.jsx
  src/utils/textRenderer.jsx
Labels: enhancement

#34 feat(router): not found page
  src/App.jsx
  src/pages/NotFound.jsx
Labels: enhancement

#35 feat(article): handle not found article case
  src/App.jsx
  src/components/NotFound.jsx
  src/modules/Article/Article.jsx
  src/pages/ArticlePage.jsx
  src/pages/Articles.jsx
  src/pages/NotFound.jsx
Labels: enhancement

#12 docs(contributing): add contributing file
  CONTRIBUTING.md
Labels: documentation

#36 fix(netlify): add article route
  netlify.toml
Labels: bug

#37 feat(theme): light and dark
  src/App.scss
  src/contexts/element.jsx
  src/modules/Nav/Theme.jsx
  src/redux/appSlice.js
Labels: enhancement

#40 add test cypress
  .github/workflows/cypress-action-test.yml
  .gitignore
  cypress.json
  cypress/integration/tests/sample_test.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#42 Added getter for redux
  src/components/AnimatedImg.jsx
  src/modules/Nav/Nav.jsx
  src/modules/Nav/Theme.jsx
  src/pages/Home.jsx
  src/redux/appSlice.js
  src/templates/VisualAndPosts.jsx
Labels: enhancement

#41 fix(light): modify sun svg to be visible
  src/assets/images/logo/day.svg
Labels: bug
